// Generated from public/exercises/sources.json (bryllim/workout-guide, CC BY-SA 4.0) and a one-off
// legibility measurement of every frame. Regenerate if the images are updated; the defaults below
// are hand-written.

/**
 * Every illustration in public/exercises, by folder name: its English name and the one frame shown.
 * The three frames of an exercise are drawn in different styles, so the app shows only the most
 * legible one: the frame whose lines are strongest when rendered at 48 px.
 */
export const CATALOG: Readonly<Record<string, readonly [name: string, frame: number]>> = {
  'ab-wheel': ['Ab Wheel Rollout', 2],
  'active-hang': ['Active Hang', 1],
  'archer-push-up': ['Archer Push-up', 2],
  'arm-circles': ['Arm Circles', 3],
  'arnold-press': ['Arnold Press', 1],
  'assault-bike': ['Assault Bike', 2],
  'assisted-chin-up': ['Assisted Chin-up', 1],
  'assisted-dip': ['Assisted Dip', 2],
  'assisted-pistol-squat': ['Assisted Pistol Squat', 2],
  'assisted-pull-up': ['Assisted Pull-up', 2],
  'back-extension': ['Back Extension', 2],
  'band-pull-apart': ['Band Pull-Apart', 3],
  'banded-clamshell': ['Banded Clamshell', 2],
  'banded-dead-bug': ['Banded Dead Bug', 2],
  'banded-donkey-kick': ['Banded Donkey Kick', 3],
  'banded-face-pull': ['Banded Face Pull', 2],
  'banded-fire-hydrant': ['Banded Fire Hydrant', 3],
  'banded-frog-pump': ['Banded Frog Pump', 1],
  'banded-glute-bridge': ['Banded Glute Bridge', 1],
  'banded-hip-thrust': ['Banded Hip Thrust', 2],
  'banded-kickback': ['Banded Kickback', 1],
  'banded-lat-pulldown': ['Banded Lat Pulldown', 1],
  'banded-lateral-walk': ['Banded Lateral Walk', 3],
  'banded-monster-walk': ['Banded Monster Walk', 2],
  'banded-pallof-press': ['Banded Pallof Press', 1],
  'banded-row': ['Banded Row', 1],
  'banded-seated-hip-abduction': ['Banded Seated Hip Abduction', 1],
  'banded-squat': ['Banded Squat', 2],
  'banded-standing-hip-abduction': ['Banded Standing Hip Abduction', 1],
  'banded-woodchop': ['Banded Woodchop', 3],
  'barbell-glute-bridge': ['Barbell Glute Bridge', 1],
  'barbell-row': ['Barbell Row', 2],
  'battle-ropes': ['Battle Ropes', 2],
  'bear-crawl': ['Bear Crawl', 3],
  'bear-plank': ['Bear Plank', 3],
  'belt-squat': ['Belt Squat', 3],
  'bench-dip': ['Bench Dip', 2],
  'bench-press': ['Bench Press', 2],
  'bent-over-rear-delt-raise': ['Bent-Over Rear Delt Raise', 3],
  'bicep-curl': ['Bicep Curl', 2],
  'bicycle-crunch': ['Bicycle Crunch', 2],
  'bird-dog': ['Bird Dog', 2],
  'bodyweight-squat': ['Bodyweight Squat', 2],
  'bulgarian-split-squat': ['Bulgarian Split Squat', 3],
  burpee: ['Burpee', 2],
  'butterfly-stretch': ['Butterfly Stretch', 3],
  'cable-crunch': ['Cable Crunch', 3],
  'cable-curl': ['Cable Curl', 2],
  'cable-fly': ['Cable Fly', 2],
  'cable-front-raise': ['Cable Front Raise', 2],
  'cable-kickback': ['Cable Kickback', 2],
  'cable-lateral-raise': ['Cable Lateral Raise', 2],
  'cable-pallof-hold': ['Cable Pallof Hold', 1],
  'cable-pull-through': ['Cable Pull-Through', 2],
  'cable-rear-delt-fly': ['Cable Rear Delt Fly', 2],
  'cable-standing-hip-abduction': ['Cable Standing Hip Abduction', 2],
  'cable-standing-hip-adduction': ['Cable Standing Hip Adduction', 1],
  'cable-woodchop': ['Cable Woodchop', 2],
  'calf-raise': ['Calf Raise', 3],
  'captains-chair-knee-raise': ["Captain's Chair Knee Raise", 2],
  'cat-cow-stretch': ['Cat-Cow Stretch', 1],
  'chair-dip': ['Chair Dip', 3],
  'chest-dip': ['Chest Dip', 2],
  'chest-supported-row': ['Chest Supported Row', 2],
  'childs-pose': ["Child's Pose", 1],
  'chin-up': ['Chin-up', 2],
  clamshell: ['Clamshell', 2],
  'close-grip-bench-press': ['Close-Grip Bench Press', 2],
  'close-grip-lat-pulldown': ['Close-Grip Lat Pulldown', 2],
  'commando-pull-up': ['Commando Pull-up', 3],
  'concentration-curl': ['Concentration Curl', 2],
  'copenhagen-plank': ['Copenhagen Plank', 2],
  'cossack-squat': ['Cossack Squat', 2],
  'crab-walk': ['Crab Walk', 3],
  'cross-body-shoulder-stretch': ['Cross-Body Shoulder Stretch', 2],
  crunch: ['Crunch', 2],
  'curtsy-lunge': ['Curtsy Lunge', 2],
  cycling: ['Cycling', 2],
  'dead-bug': ['Dead Bug', 1],
  'dead-hang': ['Dead Hang', 3],
  deadlift: ['Deadlift', 2],
  'decline-bench-press': ['Decline Bench Press', 2],
  'decline-dumbbell-press': ['Decline Dumbbell Press', 2],
  'decline-push-up': ['Decline Push-up', 2],
  'decline-sit-up': ['Decline Sit-Up', 2],
  'deficit-reverse-lunge': ['Deficit Reverse Lunge', 2],
  'diamond-push-up': ['Diamond Push-up', 2],
  dip: ['Dip', 2],
  'donkey-calf-raise': ['Donkey Calf Raise', 2],
  'donkey-kick': ['Donkey Kick', 3],
  'doorway-chest-stretch': ['Doorway Chest Stretch', 2],
  'doorway-row': ['Doorway Row', 3],
  'drag-curl': ['Drag Curl', 2],
  'dragon-flag': ['Dragon Flag', 3],
  'dumbbell-bench-press': ['Dumbbell Bench Press', 2],
  'dumbbell-bent-over-row': ['Dumbbell Bent Over Row', 3],
  'dumbbell-curtsy-lunge': ['Dumbbell Curtsy Lunge', 3],
  'dumbbell-fly': ['Dumbbell Fly', 2],
  'dumbbell-glute-bridge': ['Dumbbell Glute Bridge', 1],
  'dumbbell-hip-thrust': ['Dumbbell Hip Thrust', 3],
  'dumbbell-lateral-lunge': ['Dumbbell Lateral Lunge', 2],
  'dumbbell-overhead-tricep-extension': ['Dumbbell Overhead Tricep Extension', 2],
  'dumbbell-romanian-deadlift': ['Dumbbell Romanian Deadlift', 2],
  'dumbbell-shrug': ['Dumbbell Shrug', 2],
  'dumbbell-side-bend': ['Dumbbell Side Bend', 3],
  'dumbbell-skull-crusher': ['Two Dumbbell Skullcrusher', 2],
  'dumbbell-sumo-deadlift': ['Dumbbell Sumo Deadlift', 1],
  'dumbbell-sumo-squat': ['Dumbbell Sumo Squat', 3],
  elliptical: ['Elliptical', 2],
  'explosive-push-up': ['Explosive Push-up', 3],
  'ez-bar-curl': ['EZ-Bar Curl', 2],
  'face-pull': ['Face Pull', 3],
  'farmer-carry': ['Farmer Carry', 3],
  'fast-feet': ['Fast Feet', 2],
  'feet-elevated-pike-push-up': ['Feet-Elevated Pike Push-up', 3],
  'fire-hydrant': ['Fire Hydrant', 2],
  'flutter-kick': ['Flutter Kick', 2],
  'forward-lunge': ['Forward Lunge', 2],
  'frog-pump': ['Frog Pump', 3],
  'front-foot-elevated-split-squat': ['Front-Foot Elevated Split Squat', 2],
  'front-raise': ['Front Raise', 2],
  'front-squat': ['Front Squat', 2],
  'glute-bridge': ['Glute Bridge', 2],
  'glute-bridge-march': ['Glute Bridge March', 3],
  'glute-focused-back-extension': ['Glute-Focused Back Extension', 2],
  'goblet-squat': ['Goblet Squat', 2],
  'good-morning': ['Good Morning', 2],
  'hack-squat': ['Hack Squat', 2],
  'half-burpee': ['Half Burpee', 2],
  'half-kneeling-pallof-press': ['Half-Kneeling Pallof Press', 1],
  'hammer-curl': ['Hammer Curl', 2],
  'hamstring-stretch': ['Hamstring Stretch', 3],
  'handstand-push-up': ['Handstand Push-up', 2],
  'hanging-knee-raise': ['Hanging Knee Raise', 2],
  'hanging-leg-raise': ['Hanging Leg Raise', 2],
  'heel-elevated-goblet-squat': ['Heel-Elevated Goblet Squat', 3],
  'heel-tap': ['Heel Tap', 2],
  'high-knees': ['High Knees', 3],
  hiking: ['Hiking', 3],
  'hindu-push-up': ['Hindu Push-up', 2],
  'hip-abduction-machine': ['Hip Abduction Machine', 2],
  'hip-adduction-machine': ['Hip Adduction Machine', 3],
  'hip-airplane': ['Hip Airplane', 2],
  'hip-thrust': ['Hip Thrust', 2],
  'hollow-body-hold': ['Hollow Body Hold', 2],
  'hollow-rock': ['Hollow Rock', 3],
  inchworm: ['Inchworm', 3],
  'incline-bench-press': ['Incline Bench Press', 2],
  'incline-cable-fly': ['Incline Cable Fly', 2],
  'incline-dumbbell-curl': ['Incline Dumbbell Curl', 2],
  'incline-dumbbell-press': ['Incline Dumbbell Press', 2],
  'incline-push-up': ['Incline Push-up', 3],
  'inverted-row': ['Inverted Row', 2],
  'jump-rope': ['Jump Rope', 2],
  'jump-squat': ['Jump Squat', 2],
  'jumping-jack': ['Jumping Jack', 2],
  'kettlebell-romanian-deadlift': ['Kettlebell Romanian Deadlift', 2],
  'kettlebell-swing': ['Kettlebell Swing', 2],
  'knee-push-up': ['Knee Push-up', 2],
  'kneeling-hip-flexor-stretch': ['Kneeling Hip Flexor Stretch', 3],
  'l-sit-hold': ['L-Sit Hold', 3],
  'l-sit-pull-up': ['L-Sit Pull-up', 3],
  'landmine-press': ['Landmine Press', 2],
  'landmine-romanian-deadlift': ['Landmine Romanian Deadlift', 1],
  'landmine-squat': ['Landmine Squat', 2],
  'lat-pulldown': ['Lat Pulldown', 2],
  'lateral-lunge': ['Lateral Lunge', 2],
  'lateral-raise': ['Lateral Raise', 2],
  'lateral-shuffle': ['Lateral Shuffle', 3],
  'leg-curl': ['Leg Curl', 2],
  'leg-extension': ['Leg Extension', 2],
  'leg-press': ['Leg Press', 2],
  'leg-press-calf-raise': ['Leg Press Calf Raise', 2],
  'leg-swings-stretch': ['Leg Swings', 3],
  'lying-hamstring-walkout': ['Lying Hamstring Walkout', 3],
  'lying-leg-curl': ['Lying Leg Curl', 2],
  'lying-leg-raise': ['Lying Leg Raise', 3],
  'machine-chest-press': ['Machine Chest Press', 2],
  'machine-glute-kickback': ['Machine Glute Kickback', 1],
  'machine-lateral-raise': ['Machine Lateral Raise', 1],
  'machine-row': ['Machine Row', 2],
  'machine-shoulder-press': ['Machine Shoulder Press', 3],
  'meadows-row': ['Meadows Row', 1],
  'mountain-climber': ['Mountain Climber', 2],
  'negative-pull-up': ['Negative Pull-up', 2],
  'neutral-grip-pull-up': ['Neutral-Grip Pull-up', 2],
  'nordic-hamstring-curl': ['Nordic Hamstring Curl', 1],
  'one-arm-dumbbell-row': ['One-Arm Dumbbell Row', 3],
  'overhead-press': ['Overhead Press', 2],
  'overhead-tricep-extension': ['Overhead Tricep Extension', 3],
  'pallof-press': ['Pallof Press', 1],
  'pec-deck': ['Pec Deck', 2],
  'pendlay-row': ['Pendlay Row', 3],
  'pike-push-up': ['Pike Push-up', 1],
  'pistol-squat': ['Pistol Squat', 3],
  plank: ['Plank', 2],
  'plank-jack': ['Plank Jack', 3],
  'plank-shoulder-tap': ['Plank Shoulder Tap', 1],
  'plate-front-raise': ['Plate Front Raise', 2],
  'preacher-curl': ['Preacher Curl', 2],
  'prone-t-raise': ['Prone T Raise', 3],
  'prone-y-raise': ['Prone Y Raise', 2],
  'pull-up': ['Pull-up', 2],
  'push-press': ['Push Press', 2],
  'push-up': ['Push-up', 2],
  'push-up-shoulder-tap': ['Push-up Shoulder Tap', 3],
  'rack-pull': ['Rack Pull', 3],
  'rear-delt-fly': ['Rear Delt Fly', 2],
  'reverse-crunch': ['Reverse Crunch', 2],
  'reverse-curl': ['Reverse Curl', 2],
  'reverse-hyperextension': ['Reverse Hyperextension', 2],
  'reverse-lunge': ['Reverse Lunge', 2],
  'reverse-pec-deck': ['Reverse Pec Deck', 2],
  'reverse-snow-angel': ['Reverse Snow Angel', 2],
  'romanian-deadlift': ['Romanian Deadlift', 2],
  'rope-hammer-curl': ['Rope Hammer Curl', 2],
  'rope-tricep-pushdown': ['Rope Tricep Pushdown', 2],
  rowing: ['Rowing', 2],
  running: ['Running', 3],
  'russian-twist': ['Russian Twist', 2],
  'scapular-pull-up': ['Scapular Pull-up', 3],
  'scapular-push-up': ['Scapular Push-up', 2],
  'seal-jack': ['Seal Jack', 2],
  'seated-calf-raise': ['Seated Calf Raise', 2],
  'seated-dumbbell-press': ['Dumbbell Seated Shoulder Press', 2],
  'seated-forward-fold-stretch': ['Seated Forward Fold', 2],
  'seated-knee-tuck': ['Seated Knee Tuck', 3],
  'seated-leg-curl': ['Seated Leg Curl', 2],
  'seated-row': ['Seated Cable Row', 2],
  'shrimp-squat': ['Shrimp Squat', 1],
  shrug: ['Barbell Shrug', 3],
  'side-lying-hip-abduction': ['Side-Lying Hip Abduction', 1],
  'side-lying-leg-raise': ['Side-Lying Leg Raise', 2],
  'side-plank': ['Side Plank', 2],
  'side-plank-hip-dip': ['Side Plank Hip Dip', 1],
  'single-arm-cable-row': ['Single-Arm Cable Row', 1],
  'single-arm-dumbbell-tricep-extension': ['Single Arm Dumbbell Tricep Extension', 2],
  'single-dumbbell-skullcrusher': ['Single Dumbbell Skullcrusher', 2],
  'single-leg-box-squat': ['Single-Leg Box Squat', 2],
  'single-leg-calf-raise': ['Single-Leg Calf Raise', 1],
  'single-leg-glute-bridge': ['Single-Leg Glute Bridge', 3],
  'single-leg-romanian-deadlift': ['Single-Leg Romanian Deadlift', 2],
  'sissy-squat': ['Sissy Squat', 3],
  'skater-hop': ['Skater Hop', 1],
  'skater-squat': ['Skater Squat', 2],
  skierg: ['SkiErg', 1],
  'skull-crusher': ['Skull Crusher', 2],
  'smith-machine-bench-press': ['Smith Machine Bench Press', 2],
  'smith-machine-bulgarian-split-squat': ['Smith Machine Bulgarian Split Squat', 2],
  'smith-machine-hip-thrust': ['Smith Machine Hip Thrust', 2],
  'smith-machine-reverse-lunge': ['Smith Machine Reverse Lunge', 3],
  'smith-machine-romanian-deadlift': ['Smith Machine Romanian Deadlift', 3],
  'smith-machine-split-squat': ['Smith Machine Split Squat', 1],
  'smith-machine-squat': ['Smith Machine Squat', 2],
  'spider-curl': ['Spider Curl', 2],
  'split-squat': ['Split Squat', 3],
  sprawl: ['Sprawl', 3],
  squat: ['Squat', 2],
  'squat-thrust': ['Squat Thrust', 2],
  'stability-ball-hamstring-curl': ['Stability Ball Hamstring Curl', 3],
  'stair-climber': ['Stair Climber', 2],
  'standing-calf-raise': ['Standing Calf Raise', 2],
  'standing-dumbbell-press': ['Standing Dumbbell Press', 3],
  'standing-quad-stretch': ['Standing Quad Stretch', 1],
  'step-down': ['Step-Down', 3],
  'step-up': ['Step-Up', 2],
  'straight-arm-pulldown': ['Straight-Arm Pulldown', 2],
  'sumo-deadlift': ['Sumo Deadlift', 3],
  superman: ['Superman', 1],
  'superman-hold': ['Superman Hold', 1],
  swimming: ['Swimming', 2],
  't-bar-row': ['T-Bar Row', 2],
  'toe-touch': ['Toe Touch', 1],
  'torso-twist-stretch': ['Torso Twists', 3],
  'towel-hamstring-curl': ['Towel Hamstring Curl', 1],
  'towel-pull-up': ['Towel Pull-up', 1],
  'towel-row': ['Towel Row', 3],
  'trap-bar-deadlift': ['Trap Bar Deadlift', 3],
  'treadmill-incline-walk': ['Treadmill Incline Walk', 3],
  'tricep-kickback': ['Tricep Kickback', 2],
  'tricep-pushdown': ['Tricep Pushdown', 2],
  'typewriter-push-up': ['Typewriter Push-up', 3],
  'upright-row': ['Upright Row', 2],
  'v-up': ['V-Up', 1],
  walking: ['Walking', 3],
  'walking-lunge': ['Walking Lunge', 2],
  'wall-calf-stretch': ['Wall Calf Stretch', 2],
  'wall-handstand-push-up': ['Wall Handstand Push-up', 2],
  'wall-push-up': ['Wall Push-up', 2],
  'wall-sit': ['Wall Sit', 2],
  'wall-walk': ['Wall Walk', 2],
  'weighted-chin-up': ['Weighted Chin-up', 1],
  'weighted-crunch': ['Weighted Crunch', 1],
  'weighted-dip': ['Weighted Dip', 3],
  'weighted-pull-up': ['Weighted Pull-up', 1],
  'weighted-push-up': ['Weighted Push-up', 3],
  'weighted-russian-twist': ['Weighted Russian Twist', 2],
  'wide-grip-lat-pulldown': ['Wide-Grip Lat Pulldown', 2],
  'wide-push-up': ['Wide Push-up', 3],
  'worlds-greatest-stretch': ["World's Greatest Stretch", 3],
  'wrist-curl': ['Wrist Curl', 3],
  'wrist-extension': ['Wrist Extension', 2],
}

/**
 * The picture an exercise gets until one is chosen in the app, by its name as it came from the
 * old training log. Several are guesses; the app lets each be changed. Keys are lower case.
 */
export const DEFAULTS: Readonly<Record<string, string>> = {
  'armhävningar på hantlar': 'push-up',
  'axlar hantlar rakt upp': 'standing-dumbbell-press',
  'axlar hantlar rakt åt sidan': 'lateral-raise',
  'axlar hantlar sidan': 'lateral-raise',
  'axlar hantlar upp i bänk': 'seated-dumbbell-press',
  'axlar hantlar uppåt': 'standing-dumbbell-press',
  'axlar hantlar uppåt upprätt': 'seated-dumbbell-press',
  'benböj lår baksida': 'seated-leg-curl',
  'benböj lår framsida': 'leg-extension',
  'benböj lår maskin': 'leg-press',
  'benböj lår uppåt i maskin': 'leg-press',
  'benböj med steg framåt': 'forward-lunge',
  'biceps böjd stång': 'ez-bar-curl',
  'biceps hantlar': 'bicep-curl',
  'biceps rak stång': 'bicep-curl',
  'biceps stång': 'bicep-curl',
  'biceps stång rulla fingrar': 'wrist-curl',
  'biceps vajer': 'cable-curl',
  'biceps z-stång': 'ez-bar-curl',
  'bröst bänk sidan (ont)': 'dumbbell-fly',
  'bröst hantlar': 'incline-dumbbell-press',
  'bröst maskin': 'machine-chest-press',
  'bröst med hantlar på bänk': 'dumbbell-bench-press',
  'bröst åt sidan med hantlar': 'dumbbell-fly',
  'bröstpress maskin': 'machine-chest-press',
  bänkpress: 'bench-press',
  'bänkpress hantlar': 'dumbbell-bench-press',
  'bänkpress med hantlar': 'dumbbell-bench-press',
  'cykel till gymet': 'cycling',
  deadlift: 'deadlift',
  'dra bak i maskin': 'machine-row',
  'dra hantel upp från mark': 'one-arm-dumbbell-row',
  'dra mig upp i ringar': 'inverted-row',
  'dra ner i maskin': 'lat-pulldown',
  'dra ner stång': 'lat-pulldown',
  'dra ner stång i maskin': 'lat-pulldown',
  'dra ner två handtag i maskin': 'close-grip-lat-pulldown',
  'dra upp axlar med hantlar': 'dumbbell-shrug',
  'dra upp nacke/axlar med hantlar': 'dumbbell-shrug',
  'dra upp stång mot mage stående': 'barbell-row',
  'dra vikt bakåt maskin': 'seated-row',
  'gå upp på bänk': 'step-up',
  'gång i maskin': 'treadmill-incline-walk',
  'häng i stång': 'dead-hang',
  'häng i stång + dra mig upp i ringar': 'active-hang',
  'hänga i armarna': 'dead-hang',
  'höj ben från bänk': 'lying-leg-raise',
  'höj och sänk ben från bänk': 'lying-leg-raise',
  'höjning sänk ben liggandes på bänk': 'lying-leg-raise',
  'löpning på band': 'running',
  magmaskin: 'cable-crunch',
  'marklyft?': 'deadlift',
  plankan: 'plank',
  'pull down maskin': 'lat-pulldown',
  'pull down maskin 2': 'wide-grip-lat-pulldown',
  'sit ups': 'decline-sit-up',
  'solar rakt upp bänk': 'incline-dumbbell-press',
  squats: 'bodyweight-squat',
  'squats med kettlebell': 'goblet-squat',
  'squats med kettlebell till huvud': 'goblet-squat',
  'sänk hängande från stång': 'negative-pull-up',
  triceps: 'tricep-pushdown',
  'triceps bakåt på bänk': 'tricep-kickback',
  'triceps dips': 'bench-dip',
  'triceps maskin': 'tricep-pushdown',
  'triceps rak stång bänk': 'skull-crusher',
  'triceps rak stång i maskin': 'tricep-pushdown',
  'triceps stång på bänk': 'skull-crusher',
  'triceps sänk från bänk': 'bench-dip',
  'tricepshävningar på bänk': 'bench-dip',
  'trips rep i maskin': 'rope-tricep-pushdown',
  tåhävningar: 'standing-calf-raise',
  'underarm stång bakom': 'wrist-curl',
  'underarmar bakom rygg': 'wrist-curl',
  vader: 'standing-calf-raise',
  'vader egenvikt': 'standing-calf-raise',
}
